services:
  database:
    container_name: database
    image: postgres:17.0-alpine3.20
    restart: unless-stopped
    env_file:
      - .db.env
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgres
  redis:
    container_name: redis
    image: valkey/valkey:8.0.1-alpine3.20
    ports:
      - 6379:6379

volumes:
  database:
