services:
  # Apps
  website:
    image: egg-website:latest
    build:
      dockerfile: ./apps/website/Dockerfile
      context: .
    env_file:
      - ./apps/website/.env.docker
    ports:
      - 8080:3000
  email:
    image: egg-email:latest
    build:
      dockerfile: ./Dockerfile
      context: ./apps/email
    env_file:
      - ./apps/email/.env.docker
  # Backend services
  database:
    container_name: database
    image: postgres:17.0-alpine3.20
    restart: unless-stopped
    env_file:
      - .db.env
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgres
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.0.3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  smtp:
    container_name: smtp
    image: reachfive/fake-smtp-server
    ports:
      - 1025:1025
      - 1080:1080

volumes:
  database:
