services:
  # Apps
  website:
    build:
      dockerfile: ./apps/website/Dockerfile
      context: .
    env_file:
      - ./apps/website/.env.local
    ports:
      - 8080:3000
  # Backend services
  database:
    container_name: database
    image: postgres:17.0-alpine3.20
    restart: unless-stopped
    env_file:
      - .db.env
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgres
  redis:
    container_name: redis
    image: valkey/valkey:8.0.1-alpine3.20
    ports:
      - 6379:6379
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.0.3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  smtp:
    container_name: smtp
    image: reachfive/fake-smtp-server
    ports:
      - 1025:1025
      - 1080:1080

volumes:
  database:
